sbomify/sbomify

- .cursor/rules/django.mdc
- .cursor/rules/general.mdc
- .cursor/rules/python.mdc
- README.md
- billing/billing_processing.py
- billing/email_notifications.py
- billing/migrations/0004_add_trial_periods.py
- billing/stripe_client.py
- billing/templates/billing/emails/base.html
- billing/templates/billing/emails/subscription_ended.html
- billing/templates/billing/emails/subscription_ended.txt
- billing/templates/billing/emails/test_template.html
- billing/templates/billing/emails/test_template.txt
- billing/templates/billing/emails/trial_ending.html
- billing/templates/billing/emails/trial_ending.txt
- billing/templates/billing/emails/trial_expired.html
- billing/templates/billing/emails/trial_expired.txt
- billing/tests/fixtures.py
- billing/tests/test_billing_processing.py
- billing/tests/test_email_notifications.py
- billing/tests/test_views.py
- billing/views.py
- billing/webhook_handler.py
- sbomify/settings.py
- sbomify/test_settings.py
- teams/signals/handlers.py
- teams/templates/teams/new_user_email.html
- teams/templates/teams/new_user_email.txt
- Add trial period handling with configurable duration (TRIAL_PERIOD_DAYS)
- Add trial ending notifications with configurable threshold (TRIAL_ENDING_NOTIFICATION_DAYS)
- Add trial status tracking in billing limits
- Add trial-related subscription state handling
- Add comprehensive test coverage for trial functionality
- Add email subject prefix configuration
- Improve error handling and logging in billing processing
- Add webhook signature verification
- Add proper HTTP method restrictions for webhook endpoint
This adds support for trial periods in the billing system, allowing teams to try the service before committing to a paid plan. The implementation includes proper notification handling, status tracking, and comprehensive test coverage.
> feat(billing): add trial period functionality

- core/migrations/0002_remove_social_auth.py
- sboms/migrations/0001_initial.py
- Add migration to safely remove all data and migration records related to django-social-auth using the Django ORM.
- Make sboms Package.license_name field compatible with SQLite by adding a default value.
- All changes verified with pre-commit hooks and test database migrations.
> Remove django-social-auth data and migration records; fix sboms Package migration

- Dockerfile
- docker-compose.dev.yml
- docker-compose.yml
- docker/Dockerfile-backend-dev
- poetry.lock
- pyproject.toml
- sbomify/__init__.py
- sbomify/settings.py
- sbomify/tasks.py
- sbomify/test_settings.py
- sboms/apis.py
- sboms/apps.py
- sboms/custom_queries.py
- sboms/js/components/DashboardStats.vue
- sboms/management/commands/create_test_sbom_environment.py
- sboms/signals.py
This commit introduces background task processing using Dramatiq and Redis to handle SBOM license analysis asynchronously.
Key changes include:
- Added Dramatiq, django-redis, and redis to project dependencies.
- Configured Redis for caching and Dramatiq message broking in `settings.py`.
- Created the `process_sbom_licenses` Dramatiq task in `sbomify/tasks.py`. This task analyzes licenses from SBOM data (both main and package-specific), categorizes them, and extracts `packages_licenses` if not already present.
- Modified SBOM upload API endpoints (`sbom_upload_cyclonedx`, `sbom_upload_spdx`) in `sboms/apis.py` to trigger the `process_sbom_licenses` task after an SBOM is successfully saved.
- Refactored `get_stats_for_team` in `sboms/custom_queries.py` to use Django ORM instead of raw SQL …
> feat: Integrate Dramatiq for asynchronous SBOM license processing

- sbomify/tasks.py
- sboms/apis.py
- sboms/custom_queries.py
- sboms/tests/test_apis.py
This commit introduces several improvements to SBOM processing and license handling:
- Refactors `process_sbom_licenses` task in `sbomify/tasks.py` to fetch SBOM files from S3 instead of the local filesystem. This involves using temporary files for downloads and ensuring their cleanup.
- Adds comprehensive logging throughout the `process_sbom_licenses` task for better traceability and debugging.
- Improves error handling, including more specific logging for S3 errors and adding `exc_info=True` for detailed tracebacks.
- Implements license name normalization in `sboms/custom_queries.py` by introducing `LICENSE_NORMALIZATION_MAP`. This map standardizes various license string representations to their SPDX equivalents, improving the accuracy of license statistics.
- Updates assertions in …
> Refactor: Enhance SBOM processing and license normalization

- sboms/apis.py
- sboms/js/components/DashboardStats.vue
This commit updates the component details page to display only the uploads relevant to the currently viewed component.
- Modified `DashboardStats.vue` to include `itemId` (component_id) as a query parameter when fetching dashboard summary data if the `itemType` is 'component'.
- Updated the `/api/v1/sboms/dashboard/summary/` endpoint in `sboms/apis.py` to accept an optional `component_id` query parameter and filter the `latest_uploads` accordingly.
> feat: Filter component uploads by component ID

- sbomify/settings.py
- sboms/js/components/CiCdInfo.vue
- Remove unnecessary toast notifications and related code
- Clean up watcher functions in CiCdInfo.vue to resolve unused variable lint errors
- Remove obsolete middleware reference from Django settings
- Ensure codebase passes all Python and JS/TS linting checks
> chore: clean up notification logic and fix JS/TS lint errors

- pyproject.toml
- sboms/apis.py
- sboms/js/components/ComponentMetaInfo.spec.ts
- sboms/js/components/ComponentMetaInfo.vue
- sboms/js/components/ComponentMetaInfoDisplay.vue
- sboms/js/components/ComponentMetaInfoEditor.spec.ts
- sboms/js/components/ComponentMetaInfoEditor.vue
- sboms/schemas.py
- sboms/tests/test_apis.py
* Exposes component name and id to metadata endpoint (used by [sbomify GitHub Action](https://github.com/sbomify/github-action))
* Introduces PATCH endpoint for metadata
* Switches method to PATCH (from PUT) for editing metadata 
* Reinstates metadata copy feature
> Extend metadata and tweaks API

- sbomify/settings.py
- sbomify/tasks.py
- sboms/tests/test_vulnerability_scanning.py
- Add configurable OSV_SCANNER_TIMEOUT_SECONDS setting (default: 5 minutes)
- Increase Dramatiq task time limit from 5 to 6 minutes to provide buffer
- Implement graceful timeout error handling with user-friendly messages
- Store timeout errors in Redis for UI consumption
- Exclude TimeoutExpired from retry logic to prevent retry loops
- Add comprehensive test coverage for timeout scenarios
This resolves the TimeLimitExceeded exception reported in Sentry by ensuring the OSV scanner subprocess has a hard timeout limit that's less than the Dramatiq worker timeout, preventing hanging scans and improving system reliability.
Fixes: TimeLimitExceeded errors in scan_sbom_for_vulnerabilities task
> fix: Add robust timeout handling for OSV vulnerability scanning tasks

- core/js/components/AccessTokensList.vue
- core/js/main.ts
- core/templates/core/settings.html
- core/views.py
- sboms/templates/sboms/components_dashboard.html
- sboms/templates/sboms/products_dashboard.html
- sboms/templates/sboms/projects_dashboard.html
- teams/js/components/TeamDangerZone.vue
- teams/js/components/TeamsList.vue
- teams/js/main.ts
- teams/templates/teams/dashboard.html
- teams/templates/teams/team_details.html
- teams/tests.py
- teams/views.py
- Replace server-side rendered tables with Vue components for better interactivity
- Remove direct delete actions from products, components, and projects dashboards
- Add TeamsList.vue component for dynamic workspace management
- Refactor AccessTokensList to use Vue component with serialized data
- Prevent deletion of default workspaces with proper validation and UI feedback
- Update terminology from "Teams" to "Workspaces" throughout the application
- Add visual indicators for default workspaces and disabled states
- Improve team creation logic to handle default workspace assignment
- Add comprehensive tests for workspace deletion restrictions
- Enhance delete confirmation flows with better user experience
This change moves toward a more interactive frontend while adding important …
> refactor: migrate dashboard tables to Vue components and improve workspace management

- teams/decorators.py
- teams/tests.py
- teams/views.py
- Fix critical security vulnerability where team role validation was completely commented out
- Implement validate_role_in_current_team decorator with proper session-based role checking
- Apply decorator to all team management views requiring owner/admin access:
* team_details, team_settings, delete_team (owner only)
* delete_member, invite, delete_invite (owner only)
* set_default_team (owner/admin)
- Replace manual session role checks with centralized decorator approach
- Update tests to handle proper authentication/authorization flow
- Add session setup for role-based test scenarios
This resolves the TODO comment "Implement this" that left team access control unprotected, ensuring only users with appropriate roles can manage teams.
> security: implement team role validation decorator

- core/apis.py
- core/tests/e2e/test_critical_paths.py
- sboms/apis.py
- sboms/js/components/ComponentMetaInfo.spec.ts
- sboms/js/components/ComponentMetaInfo.vue
- sboms/js/components/ComponentMetaInfoDisplay.vue
- sboms/js/components/ComponentMetaInfoEditor.spec.ts
- sboms/js/components/ComponentMetaInfoEditor.vue
- sboms/js/components/DashboardStats.vue
- sboms/tests/test_apis.py
- Move component metadata endpoints from `/api/v1/sboms/component/{id}/meta` to `/api/v1/components/{id}/metadata`
- Replace copy metadata single endpoint with GET source + PATCH target pattern
- Move dashboard summary endpoint from `/api/v1/sboms/dashboard/summary/` to `/api/v1/dashboard/summary`
- Remove duplicate public status endpoints, use core API PATCH with `is_public` field instead
- Update all frontend components to use new API endpoints
- Update tests to reflect new endpoint structure and patterns
- Add backward compatibility aliases for removed endpoints
This refactoring improves API consistency by moving endpoints to appropriate namespaces
and following REST conventions more closely. The component metadata endpoints are now
part of the core API rather than being scattered …
> SBOM endpointsrefactor: Consolidate and standardize API endpoints

- billing/billing_processing.py
- billing/tests/fixtures.py
- billing/tests/test_api.py
- billing/tests/test_billing_processing.py
- billing/tests/test_views.py
- billing/tests/test_views_extended.py
- billing/tests/tests.py
- conftest.py
- core/tests/shared_fixtures.py
- core/tests/test_apis.py
- core/tests/test_crud_apis.py
- core/tests/test_document_tagging.py
- core/tests/test_release_api.py
- core/tests/test_sbom_tagging.py
- documents/tests/test_apis.py
- sboms/tests/test_apis.py
- teams/apis.py
- teams/tests.py
- Add shared authentication fixtures for consistent API testing across all modules
- Replace manual HTTP_AUTHORIZATION headers with standardized authenticated_api_client and guest_api_client fixtures
- Create shared_fixtures.py with reusable fixtures for teams, billing plans, and authentication
- Use get_or_create() for billing plan fixtures to prevent conflicts
- Fix team API error codes: return 404 instead of 400 for invalid team keys (better REST semantics)
- Add new team API endpoints: list_teams() and get_team() with proper authorization
- Add get_current_limits() function to billing_processing.py for centralized limit retrieval
This refactoring maintains existing test coverage while improving consistency and
reducing maintenance burden across the test suite.
> refactor: standardize API test authentication and improve team endpoints

- core/apis.py
- core/js/components/ItemsListTable.vue
- core/js/components/PaginationControls.spec.ts
- core/js/components/PaginationControls.vue
- core/management/commands/create_pagination_test_data.py
- core/schemas.py
- core/tests/test_apis.py
- documents/js/components/DocumentsTable.vue
- sboms/js/components/SbomsTable.vue
Add comprehensive pagination support to improve performance and UX when viewing large lists of SBOMs and documents on component detail pages.
Backend changes:
- Add pagination schemas (PaginationMeta, PaginatedResponse types)
- Create reusable _paginate_queryset() helper with validation
- Update /api/v1/products, /api/v1/projects, /api/v1/components endpoints
- Add new paginated endpoints:
* GET /api/v1/components/{id}/sboms
* GET /api/v1/components/{id}/documents
- Implement proper authentication and team access controls
- Include vulnerability status and release information in responses
Frontend changes:
- Create reusable PaginationControls.vue component with:
* Page navigation (Previous/Next, page numbers)
* Configurable page sizes (15, 25, 50, 100 items)
* Item count display and …
> feat: implement server-side pagination for SBOMs and Documents tables

- core/apis.py
- core/js/components/ReleaseArtifacts.vue
- core/tests/test_release_artifacts_api.py
Fix critical bug where SBOM version column displayed CDX/SPDX format versions (1.5, 2.3, 1.6) instead of actual SBOM versions.
Changes:
- Fix API responses in 3 locations where sbom_version incorrectly returned artifact.sbom.format_version instead of artifact.sbom.version
- Add missing sbom_format_version field to API responses
- Fix frontend mapping where format_version was incorrectly mapped to sbom_version field instead of sbom_format_version
- Convert artifact IDs to strings for consistency
This was causing production users to see misleading version information in the Version column of release artifacts tables, showing format versions like "1.5" instead of actual SBOM versions like SHA hashes.
Affects:
- core/apis.py: _build_release_response, list_release_artifacts, …
> fix: correct SBOM version display in release artifacts API

- core/apis.py
- core/tests/integration/test_ui_workflows.py
- core/tests/test_crud_apis.py
- Add django_auth support to /api/v1/components/{id}/sboms endpoint
- Add django_auth support to /api/v1/components/{id}/documents endpoint
- Update tests to handle new paginated response format for list_components
This resolves 401 authentication errors when Vue components try to load SBOM data from the web interface, where users are authenticated via Django sessions rather than personal access tokens.
Both endpoints now support both authentication methods:
- PersonalAccessTokenAuth (for programmatic API access)
- django_auth (for web interface users)
> fix: Enable session auth for component SBOM/document API endpoints

- .dockerignore
- sboms/tests/test_data/osv-scanner.toml
Repo is presently getting a 0 on vulns check as it's finding vulns in the test SBOMs
* Added an `osv-scanner.toml` to the test_data directory
* Added that file to .dockerignore so it doesn't impact deployments
**- How I did it**
Ran osv-scanner locally to identify the issue, then applied workaround
Tested locally with osv-scanner 1.9.2 (present scorecard version) and 2.1.0 (latest)
Scorecard for vulnerability check should be 10/10 once merged.
fix: Ensure that test_data SBOMs are skipped by scorecard vuln check
> fix: Ensure that test_data SBOMs are skipped by scorecard vuln check

- vulnerability_scanning/services.py
- vulnerability_scanning/tasks.py
- vulnerability_scanning/tests/test_services.py
- Add just-in-time health checks when no healthy servers are found in pool
- Increase health check frequency from daily to every 6 hours for more timely status updates
- Enhance health check method to properly handle degraded server status
- Improve server selection robustness to prevent "No available Dependency Track servers" errors
- Add comprehensive test coverage for new server selection logic
This resolves issues where working DT servers were incorrectly marked as unavailable due to stale health status, particularly impacting staging environment scans.
Fixes: Dependency Track scan failures with "No available servers" error
> feat: improve Dependency Track server availability with just-in-time health checks

- teams/js/components/VulnerabilitySettings.vue
- vulnerability_scanning/apis.py
- vulnerability_scanning/models.py
- vulnerability_scanning/services.py
- vulnerability_scanning/tests/test_models.py
- vulnerability_scanning/tests/test_security_fixes.py
Prevent exposure of internal Dependency Track server information (URLs and names) to end users through API responses and UI.
Changes:
- Remove server URLs from vulnerability settings API responses
- Replace server names with server IDs in vulnerability stats
- Update frontend to show generic "Managed Dependency Track server" text
- Modify model string representation to use ID instead of URL
- Remove server names from health check service responses
Security impact:
- Prevents leakage of internal infrastructure details
- Maintains functionality while improving information security
- Server IDs still allow internal tracking and debugging
Testing:
- Add comprehensive security tests to prevent regression
- Verify API responses don't expose sensitive server information
- Test billing plan …
> security: hide Dependency Track server details from end users

- .github/ISSUE_TEMPLATE/security-enhancement.md
- core/js/components/EditableSingleField.vue
- sbomify/apis.py
- teams/apis.py
- teams/js/components/TeamBranding.vue
- teams/js/components/VulnerabilitySettings.vue
- teams/schemas.py
- teams/tests.py
- vulnerability_scanning/apis.py
- vulnerability_scanning/js/components/VulnerabilityTimeSeries.vue
- vulnerability_scanning/tests/test_apis.py
- vulnerability_scanning/tests/test_security_fixes.py
Rename all team-related API endpoints to use workspace terminology while preserving internal team logic and maintaining backward compatibility.
**API Endpoints:**
- Main API router: `/teams` → `/workspaces`
- All team management endpoints updated
- All vulnerability scanning endpoints updated
- OpenAPI documentation updated with workspace terminology
**Frontend Components:**
- TeamBranding.vue: Updated all API calls to /workspaces/
- VulnerabilitySettings.vue: Updated vulnerability scanning endpoints
- VulnerabilityTimeSeries.vue: Updated all API calls
- EditableSingleField.vue: Updated team item type endpoints
**Documentation & Schemas:**
- Added comprehensive annotations explaining teams are now called workspaces
- Updated all API endpoint descriptions and summaries
- Updated schema …
> feat: rename API endpoints from /teams to /workspaces

- .github/workflows/ci-cd.yml
- pyproject.toml
- Add Docker Hub and GitHub Container Registry publishing
- Implement container image signing with Cosign for supply chain security
- Add container SBOM generation and build provenance attestations
- Upgrade to docker/build-push-action@v6 with GitHub Actions cache
- Add conditional tagging based on git refs (latest vs version tags)
- Include deployment summaries for better CI/CD visibility
- Bump version to 0.17.2
This enhancement improves the security posture and distribution capabilities of sbomify by implementing industry best practices for container publishing and supply chain security.
> feat: enhance CI/CD with multi-registry Docker publishing and container scanning

- .github/workflows/ci-cd.yml
OpenSSF Scorecard has slipped due to recent changes to the ci-cd workflow
* Ensured that all actions are pinned to a SHA
* Moved workflow permissions to jobs
**- How I did it**
* StepSecurity tool for the pinning
* Permissions based on the activities done by the jobs
Will need a release (and there's a chance that permissions aren't 100% which will then entail fixing things up before re-release).
ci: Restore dependency pinning and minimise token permissions
> ci: Restore dependency pinning and minimise token permissions
