sbomify/sbomify

DEVELOPER.md
README.md

Fixes various linting errors in Markdown.

Fixes markdown linting

---

.cursor/rules/general.mdc
.github/workflows/ci-cd.yml
Dockerfile

* Updates Bun to fix [broken release](https://bun.sh/blog/bun-v1.2.2#fixed-vite-build-regression-in-bun-v1-2-1).
* Adds Docker build to CI/CD to ensure docker builds passes.
Resolves/closes #13.

Fixes build

---

.github/workflows/ci-cd.yml
README.md
docs/deployment.md

Deprecates legacy deployment method from dedicated repository.

Deploy overhaul

---

.dockerignore
.github/workflows/ci-cd.yml
.gitignore
README.md
sbomify/test_settings.py
sboms/tests/test_models.py
test_env

This commit makes several improvements to the testing infrastructure and CI workflow:
- Switch test database from PostgreSQL to SQLite in-memory for faster test execution
- Add test_env file with safe test values for local and CI testing
- Update test assertions to handle both PostgreSQL and SQLite error messages
- Improve CI workflow:
- Split code quality and test jobs for better parallelization
- Add test matrix for running tests by module
- Optimize Docker builds with buildx caching
- Remove PostgreSQL service dependency
- Update README with improved test running instructions
- Add test_env to .dockerignore to prevent inclusion in Docker images
The changes improve test execution speed and reliability while maintaining test coverage requirements. Local development setup is simplified by …

refactor: switch to SQLite for testing and improve CI workflow

---

.pre-commit-config.yaml
README.md
billing/stripe_client.py
billing/tests/test_stripe_client.py
core/views.py
sboms/custom_queries.py

This commit improves the documentation and development setup process:
- Add detailed Poetry installation instructions
- Add step-by-step dependency installation guide
- Document pre-commit hooks setup and usage
- Fix markdown formatting in README.md
Additionally:
- Fix Stripe webhook handling to support custom secrets
- Add tests for Stripe webhook event construction
- Fix code formatting in various files (core/views.py, sboms/custom_queries.py)
- Update pre-commit config to run ruff-format before ruff
The changes improve the developer experience by providing clearer setup
instructions and ensuring consistent code formatting across the project.

improve installation docs and add pre-commit setup

---

core/admin.py
core/templates/admin/dashboard.html
core/templates/core/components/footer.html

- Add dynamic copyright year in footer using Django's now template tag
- Improve admin dashboard with:
- Cached statistics (5-minute cache)
- Better error handling and loading states
- User-friendly last login display
- Staff-only access control
- Improved chart initialization and error handling

feat: enhance admin dashboard and footer

---

.github/workflows/ci-cd.yml
README.md
docs/deployment.md

Run tests in parallel to speed things up.
Reduces wall time from ~2.2m to 1.15m.

Speedy Test-zales

---

bin/release.sh
core/management/commands/fix_migrations.py
sbomify/settings.py
vite.config.ts

* Resolves issues with manifest and related assets
* Fixes migration script locally on an empty database

Tweaks deployment script

---

poetry.lock
pyproject.toml
sbomify/tasks.py

- Add tenacity for robust retry handling with exponential backoff
- Implement 30s timeout with fail-fast approach
- Add detailed retry attempt logging
- Ensure database connection is alive before processing
- Improve error handling for database and connection errors
- Add proper exception propagation for retry mechanism
This change addresses connection issues in the SBOM license processing
task by implementing a more robust retry mechanism with proper logging
and timeout constraints.

feat(tasks): improve error handling and retry logic for SBOM processing

---

.cursor/rules/general.mdc
billing/js/billing.spec.ts
billing/js/components/PlanSelection.spec.ts
billing/templates/billing/checkout_cancel.html
billing/templates/billing/checkout_success.html
billing/tests/test_stripe_client.py
billing/tests/test_views_extended.py
billing/urls.py
billing/webhook_handler.py
tsconfig.app.json

- Add 50+ new tests for StripeClient, views, and frontend components
- Enhance webhook security with rate limiting and idempotency checks
- Add user-friendly checkout success/cancel pages
- Improve Django version compatibility
- Achieve >90% test coverage across billing module
120 tests passing, no breaking changes

feat(billing): Comprehensive test coverage and robustness improvements

---

core/js/components/DeleteConfirmationModal.spec.ts
core/js/components/DeleteConfirmationModal.vue
sboms/apis.py
sboms/js/components/DangerZone.spec.ts
sboms/js/components/DangerZone.vue
sboms/js/components/SbomUpload.spec.ts
sboms/js/components/SbomUpload.vue
sboms/js/components/SbomsTable.spec.ts
sboms/js/components/SbomsTable.vue
sboms/models.py
sboms/templates/sboms/component_details_private.html
sboms/templates/sboms/component_details_public.html
sboms/templates/sboms/sbom_details_private.html
sboms/templates/sboms/sbom_details_public.html
sboms/tests/test_apis.py
sboms/urls.py

- Add DELETE /api/v1/sboms/sbom/{sbom_id} endpoint for SBOM deletion
- Implement permission checks (owner/admin only) for SBOM deletion
- Add S3 file cleanup when deleting SBOMs
- Add comprehensive test coverage for deletion API
- Add source_display property to SBOM model for better UX
- Create reusable DeleteConfirmationModal component with full test coverage
- Enhance SbomsTable component with delete functionality:
- Add delete button with permission-based visibility
- Implement loading states during deletion
- Restructure table columns (Actions column, better organization)
- Add comprehensive test coverage for deletion workflow
- Improve SbomUpload component:
- Replace inline notifications with global notification system
- Simplify upload result handling and remove redundant state
- …

feat: Add SBOM deletion functionality and improve table management

---

billing/templates/billing/enterprise_contact.html
billing/templates/billing/select_plan.html
core/templates/core/components/onboarding_wizard.html
core/templates/socialaccount/authentication_error.html
core/templates/socialaccount/login.html
sboms/templates/sboms/component_details_public.html
sboms/templates/sboms/product_details_private.html
sboms/templates/sboms/product_details_public.html
sboms/templates/sboms/products_dashboard.html
sboms/templates/sboms/project_details_private.html
sboms/templates/sboms/project_details_public.html
sboms/templates/sboms/projects_dashboard.html
sboms/templates/sboms/sbom_details_private.html
sboms/templates/sboms/sbom_details_public.html
sboms/templates/sboms/sbom_vulnerabilities.html
sboms/templates/sboms/sboms_dashboard.html
teams/templates/teams/dashboard.html
teams/templates/teams/invite.html
templates/account/login.html

Just adds missing HTML titles.

Adds titles

---

billing/forms.py
billing/templates/billing/enterprise_contact.html
billing/urls.py
billing/views.py
sboms/js/components/DangerZone.vue
sboms/js/components/ProductDangerZone.vue
sboms/js/components/ProjectDangerZone.vue

* Resolves 404s on DELETE operations
* Fixes up enterprise page

Fixes 404s and enterprise page

---

core/admin.py
documents/admin.py
teams/admin.py

* Fixes billing in admin
* Exposes documents in admin

Admin fixes

---

core/apis.py
core/tests/test_release_apis.py

Fixes two critical release-related bugs discovered on stage:
1. **Fix release editing "already exists" error**: Enhanced PATCH endpoint to only update fields that actually changed, preventing spurious unique constraint violations when editing releases without changing names.
2. **Ensure latest releases exist proactively**: Added automatic latest release creation when users access products/releases, addressing the issue where existing products lacked latest releases.
Changes:
- Add `_ensure_latest_release_exists()` helper with error resilience
- Update PATCH logic to compare current vs new values before saving
- Call latest release creation in key access points (product details, releases list, products dashboard)
- Add comprehensive test coverage (5 new tests, 1 updated)
Resolves: Release …

fix(releases): Fix release editing errors and ensure latest releases exist

---

README.md
bin/keycloak-bootstrap.sh
docker-compose.dev.yml
docker-compose.yml

* Adds two new test users for development (jdoe/ssmith)
* Disable SSL in development mode for Keycloak

Adds test users and disable ssl in development

---

core/apis.py
core/js/components/ProductIdentifiers.vue
core/js/components/ReleasesList.vue
pyproject.toml

- Add try-catch block in list_all_releases API to handle processing errors
- Skip releases without products and log warnings
- Normalize API response fields (artifact_count vs artifacts_count)
- Make product field optional in ReleasesList component
- Add fallback UI for releases with missing product data
- Filter out invalid releases on frontend with defensive coding

fix: add error handling for releases without products

---

CONTRIBUTING.md
SECURITY.md
code_of_conduct.md

When we install Allstar it will check for various bits of boilerplate, including SECURITY.md
Added CoC, contributing guidelines and security policy
**- How I did it**
Copied (and modified where necessary) from boilerplate in .github repo
docs: Repo boilerplate

docs: Repo boilerplate

---

.github/workflows/codeql.yml

This should satisfy the need for static analysis of the Python and Javascript in this repo.
Modified from GitHub stock by adding SHAs for actions.
Run `scorecard --repo https://github.com/sbomify/sbomify` once merged
ci: Add CodeQL workflow

ci: Add CodeQL workflow

---

billing/apis.py
billing/tests/test_views.py
billing/tests/test_views_extended.py
billing/views.py
core/apis.py
core/management/commands/migrate_to_keycloak.py
core/utils.py
documents/apis.py
documents/views.py
licensing/loader.py
sbomify/tasks.py
sboms/apis.py
teams/apis.py
vulnerability_scanning/apis.py
vulnerability_scanning/clients.py
vulnerability_scanning/services.py
vulnerability_scanning/tasks.py

- Replace exception details exposure with generic error messages across all API endpoints
- Fix incomplete URL substring sanitization in Stripe checkout validation using proper URL parsing
- Remove clear-text password logging in Keycloak migration command
- Standardize error responses to prevent information leakage through exception messages
- Clean up unused imports and variables in test files
Addresses multiple security vulnerabilities:
* Information exposure through exception details (30+ instances)
* Incomplete URL substring sanitization (3 instances)
* Clear-text storage of sensitive information (1 instance)
Files affected: billing/, core/, documents/, licensing/, sboms/, teams/, vulnerability_scanning/
**- How I did it**
**- Description for …

security: Fix CodeQL security alerts and harden error handling

---

README.md

Added scorecard and best practice badges to README
Visible in rich diff
docs: Add scorecard and best practices badges

docs: Add scorecard and best practices badges

---

core/js/components/FileDragAndDrop.vue
core/tests/fixtures.py
core/tests/templates/test_base_template.py
teams/apis.py
teams/js/components/TeamBranding.vue

- Add existing file display and removal to FileDragAndDrop component
- Fix branding API URLs not updating after file changes
- Implement pending deletion state for branding files
- Add hover overlay for existing file preview
- Fix test suite with billing plans fixture and proper team setup
- Improve change detection for unsaved branding modifications
Fixes team branding file management workflow and resolves all test failures. Ensures proper session data setup in template tests for reliable CI/CD.

feat(branding): enhance file upload with existing file support and fix URL updates

---

teams/apis.py
teams/tests.py

**Problem:**
- Team branding logos were reverting to old versions after upload
- Caused by deterministic filenames creating naming collisions
- Non-atomic operations led to race conditions and caching issues
**Solution:**
- Generate unique filenames using UUIDs to eliminate collisions
- Implement atomic upload process: upload → database → cleanup
- Add proper error handling and rollback for failed operations
- Ensure old files are deleted only after successful database commit
**Changes:**
- Add UUID-based filename generation for branding assets
- Wrap database updates in atomic transactions
- Add comprehensive error handling with cleanup on failure
- Update existing tests to work with new filename format
- Add new test suite covering atomic upload behavior
**Impact:**
- Eliminates …

fix(teams): resolve branding logo reversion with atomic uploads and unique filenames

---

bin/release.sh

Clear redis cache on deploy

---

core/templates/core/base.html.j2

Fixes incorrect caching of navbar.

Fixes caching of navbar

---

sbomify/apps/core/adapters.py
sbomify/apps/core/management/commands/fix_missing_trial_subscriptions.py
sbomify/apps/teams/signals.py
sbomify/apps/teams/signals/handlers.py

- Fix OIDC email extraction in CustomSocialAccountAdapter.populate_user()
- Add explicit email extraction from OIDC data with fallback handling
- Add email validation before creating Stripe customers in all subscription creation paths
- Prevent trial subscription creation when user email is empty or missing
- Add comprehensive logging for email extraction and validation failures
Fixes issue where users with empty email addresses from OIDC callbacks would cause "Invalid address" errors when creating trial subscriptions in Stripe. The fix ensures email is properly extracted from OIDC data and validates email presence before attempting to create Stripe customers.
Affected files:
- sbomify/apps/core/adapters.py: Enhanced email extraction and validation
- sbomify/apps/teams/signals.py: Added …

fix: resolve "Invalid address" error in trial subscription creation

---

sbomify/apps/core/management/commands/fix_missing_trial_subscriptions.py

Fixes key name
